# app name
spring.application.name=air-quality-api

# tell Spring Boot we're using SQLite
spring.datasource.url=jdbc:sqlite:../air_quality.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# tell Hibernate (the database tool) to use SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# don't let Spring try to create/change our tables (we already made them in Python)
spring.jpa.hibernate.ddl-auto=none

# show us the SQL queries in the terminal (helpful for learning)
spring.jpa.show-sql=true
server.port=8081